export default Object.freeze({
  INACTIVE_GROUPS: "/inactive_groups",
  GROUPS_BY_LOCATION: "/groups_by_location",
  GROUPS_BY_UNIVERSITY: "/groups_by_university",
  GROUPS_BY_NAME: "/groups_by_name",
  GROUPS: "/groups",
  MEMBERS: "/members",
  EVENTS: "/events",
  ATTENDANTS: "/attendants",
  REQUESTS: "/requests",
  MESSAGES: "/messages",
  SOCIALMEDIA: "/social_media_profile",
  UNIVERSITIES: "/universities",
  COUNTRIES: "/countries",
  TICKETS: "/tickets",
  NOTICES: "/notices",
  ADVENTIST_ASSOCIATION_NOTICES: "/adventist_association_notices",
  ADVENTIST_UNION_NOTICES: "/adventist_union_notices",
  ADVENTIST_DIVISION_NOTICES: "/adventist_division_notices",
  ADVENTIST_ASSOCIATIONS: "/adventist_associations",
  ADVENTIST_UNIONS: "/adventist_unions",
  ADVENTIST_DIVISIONS: "/adventist_divisions",
  DIRECTOR_GROUPS: "/director_groups",
  DIRECTOR_DASHBOARD: "/director_dashboard",
});
